# Generated by Django 4.2.6 on 2023-10-17 13:27
import random

from django.db import migrations


def forward(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')

    ai_skip = random.randint(0, 2)
    for ai, a in enumerate(range(1, 4)):
        department_l0 = Department.objects.create(name=f'Region {a}')
        if ai == ai_skip:
            continue

        bi_skip = random.randint(0, 2)
        for bi, b in enumerate(('I', 'II', 'III')):
            department_l1 = Department.objects.create(
                name=f'Branch {b}',parent=department_l0)
            if bi == bi_skip:
                continue

            ci_skip = random.randint(0, 2)
            for ci, c in enumerate('ABC'):
                department_l2 = Department.objects.create(
                    name=f'Office {c}', parent=department_l1)
                if ci == ci_skip:
                    continue

                di_skip = random.randint(0, 2)
                for di, d in enumerate('XYZ'):
                    department_l3 = Department.objects.create(
                        name=f'Unit {d}', parent=department_l2)
                    if di == di_skip:
                        continue

                    for ei, e in enumerate(('Alpha', 'Beta', 'Gamma')):
                        Department.objects.create(
                            name=f'Team {e}', parent=department_l3)


def backward(apps, schema_editor):
    Department = apps.get_model('departments', 'Department')
    Department.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
